application: knurddotin
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: _site/index.html
  upload: _site/index.html
- url: /(.*)/
  static_files: _site/\1/index.html
  upload: _site/(.*)
- url: /(.*)
  static_files: _site/\1
  upload: _site/(.*)

